/*
 * Copyright (c) 2018-2021, Baikal Electronics, JSC. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <bm1000_cmu.h>
#include <bm1000_def.h>
#include <bm1000_private.h>
#include <lib/mmio.h>
#include <lib/utils_def.h>

#define MMPCIE_LCRU_GPR_S(offset)	(MMPCIE_GPR_S_BASE + offset)
#define MMPCIE_LCRU_GPR(offset)		(MMPCIE_GPR_BASE + offset)

#define MMPCIE_LCRU_GPR_PCIE_MM_RESET_REG	MMPCIE_LCRU_GPR(0x80)
enum {
	MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_SLV_X4_0_RST = BIT(0),
	MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_SLV_X4_1_RST = BIT(1),
	MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_SLV_X8_RST   = BIT(2),
	MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_SLV_SLV_RST  = BIT(3),
	MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_CFG_X4_0_RST = BIT(4),
	MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_CFG_X4_1_RST = BIT(5),
	MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_CFG_X8_RST   = BIT(6),
	MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_CFG_SLV_RST  = BIT(7),
	MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_CFG_TCU_RST  = BIT(8)
};

#define MMPCIE_LCRU_GPR_PCIE_X4_0_SID_PROT_CTL_REG	MMPCIE_LCRU_GPR(0xd0)
#define MMPCIE_LCRU_GPR_PCIE_X4_1_SID_PROT_CTL_REG	MMPCIE_LCRU_GPR(0xd8)
#define MMPCIE_LCRU_GPR_PCIE_X8_SID_PROT_CTL_REG	MMPCIE_LCRU_GPR(0xe0)
#define MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_AWPROT(x)	SETMASK(x,  2, 0)
#define MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_WSID_MODE	BIT(5)
#define MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_ARPROT(x)	SETMASK(x, 10, 8)
#define MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_RSID_MODE	BIT(13)

#define MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL0_REG			MMPCIE_LCRU_GPR(0xe8)
#define MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL0_MSI_AWUSER_MASK	GENMASK(3, 0)

#define MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL2_REG				MMPCIE_LCRU_GPR(0xf8)
#define MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL2_MSI_RCNUM_PCIE_X4_0_MASK	GENMASK(1, 0)
#define MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL2_MSI_RCNUM_PCIE_X4_1_MASK	GENMASK(3, 2)
#define MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL2_MSI_RCNUM_PCIE_X8_MASK	GENMASK(5, 4)
#define MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL2_PCIE_X4_0_MSI_TRANS_EN	BIT(9)
#define MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL2_PCIE_X4_1_MSI_TRANS_EN	BIT(10)
#define MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL2_PCIE_X8_MSI_TRANS_EN	BIT(11)

void mmpcie_init(void)
{
	uint32_t reg;
	static const cmu_pll_ctl_vals_t mmpcie_lcru_pll_init = {
		0, 0, 0x78, 0, 0, 0x2c, 0, 0x2c
	};

	cmu_pll_on(MMPCIE_CMU0_BASE, &mmpcie_lcru_pll_init);

	cmu_clkch_enable_by_base(MMPCIE_CMU0_CLKCHCTL_X4_0_MSTR,  4); /* 375 MHz */
	cmu_clkch_enable_by_base(MMPCIE_CMU0_CLKCHCTL_X4_0_SLV,   4); /* 375 MHz */
	cmu_clkch_enable_by_base(MMPCIE_CMU0_CLKCHCTL_X4_0_CFG,  30); /*  50 MHz */
	cmu_clkch_enable_by_base(MMPCIE_CMU0_CLKCHCTL_X4_1_MSTR,  4); /* 375 MHz */
	cmu_clkch_enable_by_base(MMPCIE_CMU0_CLKCHCTL_X4_1_SLV,   4); /* 375 MHz */
	cmu_clkch_enable_by_base(MMPCIE_CMU0_CLKCHCTL_X4_1_CFG,  30); /*  50 MHz */
	cmu_clkch_enable_by_base(MMPCIE_CMU0_CLKCHCTL_X8_MSTR,    3); /* 500 MHz */
	cmu_clkch_enable_by_base(MMPCIE_CMU0_CLKCHCTL_X8_SLV,     3); /* 500 MHz */
	cmu_clkch_enable_by_base(MMPCIE_CMU0_CLKCHCTL_X8_CFG,    30); /*  50 MHz */
	cmu_clkch_enable_by_base(MMPCIE_CMU0_CLKCHCTL_TCU_CFG,    4); /* 375 MHz */
	cmu_clkch_enable_by_base(MMPCIE_CMU0_CLKCHCTL_TBU0,       4); /* 375 MHz */
	cmu_clkch_enable_by_base(MMPCIE_CMU0_CLKCHCTL_TBU1,       4); /* 375 MHz */
	cmu_clkch_enable_by_base(MMPCIE_CMU0_CLKCHCTL_TBU2,       3); /* 500 MHz */

	/* Deassert reset signals */
	reg = mmio_read_32(MMPCIE_LCRU_GPR_PCIE_MM_RESET_REG);
	reg &= ~(MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_CFG_X4_0_RST	|
		 MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_CFG_X4_1_RST	|
		 MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_CFG_X8_RST	|
		 MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_CFG_TCU_RST);

	mmio_write_32(MMPCIE_LCRU_GPR_PCIE_MM_RESET_REG, reg);
	reg &= ~MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_CFG_SLV_RST;
	mmio_write_32(MMPCIE_LCRU_GPR_PCIE_MM_RESET_REG, reg);
	reg &= ~(MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_SLV_X4_0_RST |
		 MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_SLV_X4_1_RST |
		 MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_SLV_X8_RST);

	mmio_write_32(MMPCIE_LCRU_GPR_PCIE_MM_RESET_REG, reg);
	reg &= ~MMPCIE_LCRU_GPR_PCIE_MM_RESET_NIC_SLV_SLV_RST;
	mmio_write_32(MMPCIE_LCRU_GPR_PCIE_MM_RESET_REG, reg);

	/* Set MSI_AWUSER to 0 */
	mmio_clrbits_32(MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL0_REG,
			MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL0_MSI_AWUSER_MASK);

	/* Enable MSI translations, RC number for all MSI transactions is 0 */
	mmio_clrsetbits_32(MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL2_REG,
			   MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL2_MSI_RCNUM_PCIE_X4_0_MASK |
			   MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL2_MSI_RCNUM_PCIE_X4_1_MASK |
			   MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL2_MSI_RCNUM_PCIE_X8_MASK,
			   MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL2_PCIE_X4_0_MSI_TRANS_EN |
			   MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL2_PCIE_X4_1_MSI_TRANS_EN |
			   MMPCIE_LCRU_GPR_PCIE_MSI_TRANS_CTL2_PCIE_X8_MSI_TRANS_EN);

	/* Enable non-secure access to some LCRU GPRs */
	mmio_write_32(MMPCIE_LCRU_GPR_S(0), 0x171717);

	/* Configure SMMU StreamID interface */
	mmio_write_32(MMPCIE_LCRU_GPR_PCIE_X4_0_SID_PROT_CTL_REG,
		      MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_AWPROT(2) |
		      MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_ARPROT(2) |
		      MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_WSID_MODE |
		      MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_RSID_MODE);

	mmio_write_32(MMPCIE_LCRU_GPR_PCIE_X4_1_SID_PROT_CTL_REG,
		      MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_AWPROT(2) |
		      MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_ARPROT(2) |
		      MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_WSID_MODE |
		      MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_RSID_MODE);

	mmio_write_32(MMPCIE_LCRU_GPR_PCIE_X8_SID_PROT_CTL_REG,
		      MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_AWPROT(2) |
		      MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_ARPROT(2) |
		      MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_WSID_MODE |
		      MMPCIE_LCRU_GPR_PCIE_SID_PROT_CTL_RSID_MODE);

	/* Enable non-secure access */
	mmio_write_32(MMPCIE_NIC_CFG_GPV_REGIONSEC_SMMU, NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMPCIE_NIC_CFG_GPV_REGIONSEC_X4_0, NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMPCIE_NIC_CFG_GPV_REGIONSEC_X4_1, NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMPCIE_NIC_CFG_GPV_REGIONSEC_X8,	 NIC_GPV_REGIONSEC_NONSECURE);

	mmio_write_32(MMPCIE_NIC_GPV_REGIONSEC_X4_0, NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMPCIE_NIC_GPV_REGIONSEC_X4_1, NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMPCIE_NIC_GPV_REGIONSEC_X8,   NIC_GPV_REGIONSEC_NONSECURE);
}
