/** @file  baikal_hdmi.h

 Copyright (C) 2020 Baikal Electronics JSC

 Author: Pavel Parkhomenko <Pavel.Parkhomenko@baikalelectronics.ru>

 Parts of this file were based on sources as follows:

 Copyright (c) 2011, ARM Ltd. All rights reserved.<BR>
 SPDX-License-Identifier: BSD-2-Clause-Patent

 **/

#ifndef __BAIKAL_HDMI_H
#define __BAIKAL_HDMI_H

#define HDMI_REG_WIDTH	4

#define MMXGBE_HDMI_BASE 0x30280000

/* Interrupt Registers */
#define BAIKAL_HDMI_IH_I2CMPHY_STAT0      (MMXGBE_HDMI_BASE + 0x0108 * HDMI_REG_WIDTH)

#define BAIKAL_HDMI_PHY_CONF0             (MMXGBE_HDMI_BASE + 0x3000 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_PHY_TST0              (MMXGBE_HDMI_BASE + 0x3001 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_PHY_STAT0             (MMXGBE_HDMI_BASE + 0x3004 * HDMI_REG_WIDTH)

/* Video Sample Registers */
#define BAIKAL_HDMI_TX_INVID0             (MMXGBE_HDMI_BASE + 0x0200 * HDMI_REG_WIDTH)

/* Frame Composer Registers */
#define BAIKAL_HDMI_FC_INVIDCONF          (MMXGBE_HDMI_BASE + 0x1000 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_INHACTV0           (MMXGBE_HDMI_BASE + 0x1001 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_INHACTV1           (MMXGBE_HDMI_BASE + 0x1002 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_INHBLANK0          (MMXGBE_HDMI_BASE + 0x1003 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_INHBLANK1          (MMXGBE_HDMI_BASE + 0x1004 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_INVACTV0           (MMXGBE_HDMI_BASE + 0x1005 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_INVACTV1           (MMXGBE_HDMI_BASE + 0x1006 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_INVBLANK           (MMXGBE_HDMI_BASE + 0x1007 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_HSYNCINDELAY0      (MMXGBE_HDMI_BASE + 0x1008 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_HSYNCINDELAY1      (MMXGBE_HDMI_BASE + 0x1009 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_HSYNCINWIDTH0      (MMXGBE_HDMI_BASE + 0x100A * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_HSYNCINWIDTH1      (MMXGBE_HDMI_BASE + 0x100B * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_VSYNCINDELAY       (MMXGBE_HDMI_BASE + 0x100C * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_VSYNCINWIDTH       (MMXGBE_HDMI_BASE + 0x100D * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_CTRLDUR            (MMXGBE_HDMI_BASE + 0x1011 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_EXCTRLDUR          (MMXGBE_HDMI_BASE + 0x1012 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_EXCTRLSPAC         (MMXGBE_HDMI_BASE + 0x1013 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_CH0PREAM           (MMXGBE_HDMI_BASE + 0x1014 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_CH1PREAM           (MMXGBE_HDMI_BASE + 0x1015 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_CH2PREAM           (MMXGBE_HDMI_BASE + 0x1016 * HDMI_REG_WIDTH)

/* Frame Composer Debug Registers */
#define BAIKAL_HDMI_FC_DBGFORCE           (MMXGBE_HDMI_BASE + 0x1200 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_DBGTMDS0           (MMXGBE_HDMI_BASE + 0x1219 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_DBGTMDS1           (MMXGBE_HDMI_BASE + 0x121A * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_FC_DBGTMDS2           (MMXGBE_HDMI_BASE + 0x121B * HDMI_REG_WIDTH)

/* Main Controller Registers */
#define BAIKAL_HDMI_MC_CLKDIS             (MMXGBE_HDMI_BASE + 0x4001 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_MC_PHYRSTZ            (MMXGBE_HDMI_BASE + 0x4005 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_MC_HEACPHY_RST        (MMXGBE_HDMI_BASE + 0x4007 * HDMI_REG_WIDTH)

/* HDMI Master PHY Registers */
#define BAIKAL_HDMI_PHY_I2CM_SLAVE_ADDR                (MMXGBE_HDMI_BASE + 0x3020 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_PHY_I2CM_ADDRESS_ADDR              (MMXGBE_HDMI_BASE + 0x3021 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_PHY_I2CM_DATAO_1_ADDR              (MMXGBE_HDMI_BASE + 0x3022 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_PHY_I2CM_DATAO_0_ADDR              (MMXGBE_HDMI_BASE + 0x3023 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_PHY_I2CM_DATAI_1_ADDR              (MMXGBE_HDMI_BASE + 0x3024 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_PHY_I2CM_DATAI_0_ADDR              (MMXGBE_HDMI_BASE + 0x3025 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_PHY_I2CM_OPERATION_ADDR            (MMXGBE_HDMI_BASE + 0x3026 * HDMI_REG_WIDTH)
#define BAIKAL_HDMI_PHY_I2CM_INT_ADDR                  (MMXGBE_HDMI_BASE + 0x3027 * HDMI_REG_WIDTH)

#define BAIKAL_HDMI_PHY_I2CM_SLAVE_ADDR_PHY_GEN2       0x69

#define BAIKAL_HDMI_PHY_OPMODE_PLLCFG   0x06    /* Mode of operation and PLL dividers */
#define BAIKAL_HDMI_PHY_PLLCURRCTRL     0x10    /* PLL current */
#define BAIKAL_HDMI_PHY_PLLGMPCTRL      0x15    /* PLL Gmp (conductance) */
#define BAIKAL_HDMI_PHY_TXTERM          0x19    /* Rterm */
#define BAIKAL_HDMI_PHY_VLEVCTRL        0x0e    /* Voltage levels */
#define BAIKAL_HDMI_PHY_CKSYMTXCTRL     0x09    /* Tx symbols control and slope boost */

enum {

/* PHY_TST0 field values */
	BAIKAL_HDMI_PHY_TST0_TSTCLR_MASK = 0x20,

/* PHY_STAT0 field values */
	BAIKAL_HDMI_PHY_TX_PHY_LOCK = 0x01,

/* TX_INVID0 field values */
	BAIKAL_HDMI_TX_INVID0_VIDEO_MAPPING_MASK = 0x1F,
	BAIKAL_HDMI_TX_INVID0_VIDEO_MAPPING_OFFSET = 0,

/* FC_INVIDCONF field values */
	BAIKAL_HDMI_FC_INVIDCONF_VSYNC_IN_POLARITY_MASK = 0x40,
	BAIKAL_HDMI_FC_INVIDCONF_VSYNC_IN_POLARITY_ACTIVE_HIGH = 0x40,
	BAIKAL_HDMI_FC_INVIDCONF_VSYNC_IN_POLARITY_ACTIVE_LOW = 0x00,
	BAIKAL_HDMI_FC_INVIDCONF_HSYNC_IN_POLARITY_MASK = 0x20,
	BAIKAL_HDMI_FC_INVIDCONF_HSYNC_IN_POLARITY_ACTIVE_HIGH = 0x20,
	BAIKAL_HDMI_FC_INVIDCONF_HSYNC_IN_POLARITY_ACTIVE_LOW = 0x00,
	BAIKAL_HDMI_FC_INVIDCONF_DE_IN_POLARITY_MASK = 0x10,
	BAIKAL_HDMI_FC_INVIDCONF_DE_IN_POLARITY_ACTIVE_HIGH = 0x10,
	BAIKAL_HDMI_FC_INVIDCONF_DE_IN_POLARITY_ACTIVE_LOW = 0x00,
	BAIKAL_HDMI_FC_INVIDCONF_DVI_MODEZ_MASK = 0x8,
	BAIKAL_HDMI_FC_INVIDCONF_DVI_MODEZ_HDMI_MODE = 0x8,
	BAIKAL_HDMI_FC_INVIDCONF_DVI_MODEZ_DVI_MODE = 0x0,
	BAIKAL_HDMI_FC_INVIDCONF_R_V_BLANK_IN_OSC_MASK = 0x2,
	BAIKAL_HDMI_FC_INVIDCONF_R_V_BLANK_IN_OSC_ACTIVE_HIGH = 0x2,
	BAIKAL_HDMI_FC_INVIDCONF_R_V_BLANK_IN_OSC_ACTIVE_LOW = 0x0,
	BAIKAL_HDMI_FC_INVIDCONF_IN_I_P_MASK = 0x1,
	BAIKAL_HDMI_FC_INVIDCONF_IN_I_P_INTERLACED = 0x1,
	BAIKAL_HDMI_FC_INVIDCONF_IN_I_P_PROGRESSIVE = 0x0,

/* PHY_CONF0 field values */
	BAIKAL_HDMI_PHY_CONF0_PDZ_MASK = 0x80,
	BAIKAL_HDMI_PHY_CONF0_PDZ_OFFSET = 7,
	BAIKAL_HDMI_PHY_CONF0_ENTMDS_MASK = 0x40,
	BAIKAL_HDMI_PHY_CONF0_ENTMDS_OFFSET = 6,
	BAIKAL_HDMI_PHY_CONF0_SPARECTRL_MASK = 0x20,
	BAIKAL_HDMI_PHY_CONF0_SPARECTRL_OFFSET = 5,
	BAIKAL_HDMI_PHY_CONF0_GEN2_PDDQ_MASK = 0x10,
	BAIKAL_HDMI_PHY_CONF0_GEN2_PDDQ_OFFSET = 4,
	BAIKAL_HDMI_PHY_CONF0_GEN2_TXPWRON_MASK = 0x8,
	BAIKAL_HDMI_PHY_CONF0_GEN2_TXPWRON_OFFSET = 3,
	BAIKAL_HDMI_PHY_CONF0_GEN2_ENHPDRXSENSE_MASK = 0x4,
	BAIKAL_HDMI_PHY_CONF0_GEN2_ENHPDRXSENSE_OFFSET = 2,
	BAIKAL_HDMI_PHY_CONF0_SELDATAENPOL_MASK = 0x2,
	BAIKAL_HDMI_PHY_CONF0_SELDATAENPOL_OFFSET = 1,
	BAIKAL_HDMI_PHY_CONF0_SELDIPIF_MASK = 0x1,
	BAIKAL_HDMI_PHY_CONF0_SELDIPIF_OFFSET = 0,

/* PHY_I2CM_OPERATION_ADDR field values */
	BAIKAL_HDMI_PHY_I2CM_OPERATION_ADDR_WRITE = 0x10,
	BAIKAL_HDMI_PHY_I2CM_OPERATION_ADDR_READ = 0x1,

/* MC_CLKDIS field values */
	BAIKAL_HDMI_MC_CLKDIS_HDCPCLK_DISABLE = 0x40,
	BAIKAL_HDMI_MC_CLKDIS_CECCLK_DISABLE = 0x20,
	BAIKAL_HDMI_MC_CLKDIS_CSCCLK_DISABLE = 0x10,
	BAIKAL_HDMI_MC_CLKDIS_AUDCLK_DISABLE = 0x8,
	BAIKAL_HDMI_MC_CLKDIS_PREPCLK_DISABLE = 0x4,
	BAIKAL_HDMI_MC_CLKDIS_TMDSCLK_DISABLE = 0x2,
	BAIKAL_HDMI_MC_CLKDIS_PIXELCLK_DISABLE = 0x1,

/* MC_PHYRSTZ field values */
	BAIKAL_HDMI_MC_PHYRSTZ_ASSERT = 0x0,
	BAIKAL_HDMI_MC_PHYRSTZ_DEASSERT = 0x1,

/* MC_HEACPHY_RST field values */
	BAIKAL_HDMI_MC_HEACPHY_RST_ASSERT = 0x1,
	BAIKAL_HDMI_MC_HEACPHY_RST_DEASSERT = 0x0,

};

#endif /* __BAIKAL_HDMI_H */
