/*
 * Copyright (c) 2018-2021, Baikal Electronics, JSC. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <lib/mmio.h>
#include <lib/utils_def.h>

#include <baikal_def.h>
#include <bm1000_cmu.h>
#include <bm1000_private.h>
#include <dw_gpio.h>

#define MMXGBE_ASYNCRES_REG			(MMXGBE_GPR_BASE + 0x00)
#define MMXGBE_ASYNCRES_REG_CFG_NICS_RES	BIT(0)
#define MMXGBE_ASYNCRES_REG_CFG_NICM_RES	BIT(1)
#define MMXGBE_ASYNCRES_REG_DMA_NICS_RES	BIT(2)
#define MMXGBE_ASYNCRES_REG_DMA_NICM_RES	BIT(3)
#define MMXGBE_ASYNCRES_REG_XGBE0_PWRON_RES	BIT(4)
#define MMXGBE_ASYNCRES_REG_XGBE1_PWRON_RES	BIT(8)
#define MMXGBE_ASYNCRES_REG_HDMI_PWRON_RES	BIT(12)

#define MMXGBE_GMAC0_PROT_CTL_REG		(MMXGBE_GPR_BASE + 0x18)
#define MMXGBE_GMAC1_PROT_CTL_REG		(MMXGBE_GPR_BASE + 0x20)
#define MMXGBE_GMAC_PROT_CTL_REG_AWPROT_MASK	GENMASK(   2, 0)
#define MMXGBE_GMAC_PROT_CTL_REG_AWPROT(x)	SETMASK(x, 2, 0)
#define MMXGBE_GMAC_PROT_CTL_REG_ARPROT_MASK	GENMASK(   5, 3)
#define MMXGBE_GMAC_PROT_CTL_REG_ARPROT(x)	SETMASK(x, 5, 3)

#define MMXGBE_GMAC0_CACHE_CTL_REG		(MMXGBE_GPR_BASE + 0x90)
#define MMXGBE_GMAC1_CACHE_CTL_REG		(MMXGBE_GPR_BASE + 0x98)
#define MMXGBE_GMAC_CACHE_CTL_REG_ARCACHE(x)	SETMASK(x,  3,  0)
#define MMXGBE_GMAC_CACHE_CTL_REG_ARDOMAIN(x)	SETMASK(x,  9,  8)
#define MMXGBE_GMAC_CACHE_CTL_REG_AWCACHE(x)	SETMASK(x, 19, 16)
#define MMXGBE_GMAC_CACHE_CTL_REG_AWDOMAIN(x)	SETMASK(x, 25, 24)

#define MMXGBE_XGBE0_PROT_CTL_REG		(MMXGBE_GPR_BASE + 0x08)
#define MMXGBE_XGBE0_PROT_CTL_REG_AWPROT_MASK	GENMASK(   2, 0)
#define MMXGBE_XGBE0_PROT_CTL_REG_AWPROT(x)	SETMASK(x, 2, 0)
#define MMXGBE_XGBE0_PROT_CTL_REG_ARPROT_MASK	GENMASK(   5, 3)
#define MMXGBE_XGBE0_PROT_CTL_REG_ARPROT(x)	SETMASK(x, 5, 3)

#define MMXGBE_XGBE1_PROT_CTL_REG		(MMXGBE_GPR_BASE + 0x10)
#define MMXGBE_XGBE1_PROT_CTL_REG_AWPROT_MASK	GENMASK(   2, 0)
#define MMXGBE_XGBE1_PROT_CTL_REG_AWPROT(x)	SETMASK(x, 2, 0)
#define MMXGBE_XGBE1_PROT_CTL_REG_ARPROT_MASK	GENMASK(   5, 3)
#define MMXGBE_XGBE1_PROT_CTL_REG_ARPROT(x)	SETMASK(x, 5, 3)

#define MMXGBE_HDMI_VIDEO_PROT_CTL_REG		(MMXGBE_GPR_BASE + 0x28)
#define MMXGBE_HDMI_VIDEO_PROT_CTL_REG_ARPROT(x)	SETMASK(x, 5, 3)
#define MMXGBE_HDMI_VIDEO_PROT_CTL_REG_ARPROT_MASK	SETMASK(x, 5, 3)

#define MMXGBE_HDMI_VIDEO_QOS_CTL_REG		(MMXGBE_GPR_BASE + 0x78)
#define MMXGBE_HDMI_VIDEO_QOS_CTL_REG_ARQOS(x)		SETMASK(x, 7, 4)

#define MMXGBE_HDMI_VIDEO_CACHE_CTL_REG		(MMXGBE_GPR_BASE + 0xa0)
#define MMXGBE_HDMI_VIDEO_CACHE_CTL_REG_ARCACHE(x)	SETMASK(x, 3, 0)
#define MMXGBE_HDMI_VIDEO_CACHE_CTL_REG_ARDOMAIN(x)	SETMASK(x, 9, 8)

#define MMXGBE_HDMI_AUDIO_PROT_CTL_REG		(MMXGBE_GPR_BASE + 0x30)
#define MMXGBE_HDMI_AUDIO_PROT_CTL_REG_ARPROT(x)	SETMASK(x, 5, 3)
#define MMXGBE_HDMI_AUDIO_PROT_CTL_REG_ARPROT_MASK	SETMASK(x, 5, 3)

#define MMXGBE_HDMI_AUDIO_QOS_CTL_REG		(MMXGBE_GPR_BASE + 0x80)
#define MMXGBE_HDMI_AUDIO_QOS_CTL_REG_ARQOS(x)		SETMASK(x, 7, 4)

#define MMXGBE_HDMI_AUDIO_CACHE_CTL_REG		(MMXGBE_GPR_BASE + 0xa8)
#define MMXGBE_HDMI_AUDIO_CACHE_CTL_REG_ARCACHE(x)	SETMASK(x, 3, 0)
#define MMXGBE_HDMI_AUDIO_CACHE_CTL_REG_ARDOMAIN(x)	SETMASK(x, 9, 8)

void mmxgbe_init(void)
{
	const cmu_pll_ctl_vals_t mmxgbe_cmu0_pll_ctls = { 0, 0,    0x64, 0, 0, 0x2c, 0, 0x2c };
	const cmu_pll_ctl_vals_t mmxgbe_cmu1_pll_ctls = { 0, 0x6b, 0xca, 0, 0, 0x2c, 0, 0x2c }; /* 25.25 MHz */

	mmio_clrbits_32(MMXGBE_ASYNCRES_REG,
			MMXGBE_ASYNCRES_REG_CFG_NICS_RES |
			MMXGBE_ASYNCRES_REG_CFG_NICM_RES |
			MMXGBE_ASYNCRES_REG_DMA_NICS_RES |
			MMXGBE_ASYNCRES_REG_DMA_NICM_RES);

#ifdef BAIKAL_HDMI_CLKEN_GPIO_PIN
	gpio_out_rst(MMAVLSP_GPIO32_BASE, BAIKAL_HDMI_CLKEN_GPIO_PIN);
	gpio_dir_set(MMAVLSP_GPIO32_BASE, BAIKAL_HDMI_CLKEN_GPIO_PIN);
#endif

	cmu_pll_on(MMXGBE_CMU0_BASE, &mmxgbe_cmu0_pll_ctls);
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_CSR0,	       25); /*  50.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_CSR1,	       12); /* 104.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_XGBE0_REF,        8); /* 156.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_XGBE0_AXI,        5); /* 250.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_XGBE0_PTP,        8); /* 156.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_XGBE1_REF,        8); /* 156.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_XGBE1_AXI,        5); /* 250.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_XGBE1_PTP,        8); /* 156.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_GMAC0_AXI,        5); /* 250.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_GMAC0_PTP,       10); /* 125.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_GMAC0_TX2,        5); /* 250.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_GMAC1_AXI,        5); /* 250.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_GMAC1_PTP,       10); /* 125.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_GMAC1_TX2,        5); /* 250.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_SMMU,             3); /* 416.7 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_HDMI_VDU_ACLK,    2); /* 625.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_HDMI_AUDIO_ACLK, 10); /* 125.0 MHz */
	cmu_clkch_enable_by_base(MMXGBE_CMU0_CLKCHCTL_HDMI_SFR0,       50); /*  25.0 MHz */

	cmu_pll_on(MMXGBE_CMU1_BASE, &mmxgbe_cmu1_pll_ctls);
	cmu_clkch_enable_by_base(MMXGBE_CMU1_CLKCHCTL_HDMI_SFR1,        1); /* 594.0 MHz */

	/* Deassert XGMAC resets */
	mmio_clrbits_32(MMXGBE_ASYNCRES_REG,
			MMXGBE_ASYNCRES_REG_XGBE0_PWRON_RES |
			MMXGBE_ASYNCRES_REG_XGBE1_PWRON_RES |
			MMXGBE_ASYNCRES_REG_HDMI_PWRON_RES);

	/* GMAC - Domain 2, cached */
	mmio_write_32(MMXGBE_GMAC0_CACHE_CTL_REG,
		      MMXGBE_GMAC_CACHE_CTL_REG_ARDOMAIN(2)  |
		      MMXGBE_GMAC_CACHE_CTL_REG_AWDOMAIN(2)  |
		      MMXGBE_GMAC_CACHE_CTL_REG_ARCACHE(0xb) |
		      MMXGBE_GMAC_CACHE_CTL_REG_AWCACHE(0x7));

	mmio_write_32(MMXGBE_GMAC1_CACHE_CTL_REG,
		      MMXGBE_GMAC_CACHE_CTL_REG_ARDOMAIN(2)  |
		      MMXGBE_GMAC_CACHE_CTL_REG_AWDOMAIN(2)  |
		      MMXGBE_GMAC_CACHE_CTL_REG_ARCACHE(0xb) |
		      MMXGBE_GMAC_CACHE_CTL_REG_AWCACHE(0x7));

	/* VDU, HDMI */
	mmio_write_32(MMXGBE_HDMI_VIDEO_CACHE_CTL_REG,
		      MMXGBE_HDMI_VIDEO_CACHE_CTL_REG_ARDOMAIN(2) |
		      MMXGBE_HDMI_VIDEO_CACHE_CTL_REG_ARCACHE(0xb));

	mmio_write_32(MMXGBE_HDMI_VIDEO_QOS_CTL_REG,
		      MMXGBE_HDMI_VIDEO_QOS_CTL_REG_ARQOS(0xf));

	mmio_write_32(MMXGBE_HDMI_AUDIO_CACHE_CTL_REG,
		      MMXGBE_HDMI_AUDIO_CACHE_CTL_REG_ARDOMAIN(2) |
		      MMXGBE_HDMI_AUDIO_CACHE_CTL_REG_ARCACHE(0xb));
}

void mmxgbe_ns_access(void)
{
	mmio_write_32(MMXGBE_GMAC0_PROT_CTL_REG,
		      MMXGBE_GMAC_PROT_CTL_REG_AWPROT(2) |
		      MMXGBE_GMAC_PROT_CTL_REG_ARPROT(2));

	mmio_write_32(MMXGBE_GMAC1_PROT_CTL_REG,
		      MMXGBE_GMAC_PROT_CTL_REG_AWPROT(2) |
		      MMXGBE_GMAC_PROT_CTL_REG_ARPROT(2));

	mmio_write_32(MMXGBE_XGBE0_PROT_CTL_REG,
		      MMXGBE_XGBE0_PROT_CTL_REG_AWPROT(2) |
		      MMXGBE_XGBE0_PROT_CTL_REG_ARPROT(2));

	mmio_write_32(MMXGBE_XGBE1_PROT_CTL_REG,
		      MMXGBE_XGBE1_PROT_CTL_REG_AWPROT(2) |
		      MMXGBE_XGBE1_PROT_CTL_REG_ARPROT(2));

	mmio_write_32(MMXGBE_HDMI_VIDEO_PROT_CTL_REG,
		      MMXGBE_HDMI_VIDEO_PROT_CTL_REG_ARPROT(2));

	mmio_write_32(MMXGBE_HDMI_AUDIO_PROT_CTL_REG,
		      MMXGBE_HDMI_AUDIO_PROT_CTL_REG_ARPROT(2));

	mmio_write_32(MMXGBE_NIC_CFG_GPV_REGIONSEC_VDU,	       NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMXGBE_NIC_CFG_GPV_REGIONSEC_XGBE0_CTRL, NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMXGBE_NIC_CFG_GPV_REGIONSEC_XGBE0_PHY,  NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMXGBE_NIC_CFG_GPV_REGIONSEC_XGBE1_CTRL, NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMXGBE_NIC_CFG_GPV_REGIONSEC_XGBE1_PHY,  NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMXGBE_NIC_CFG_GPV_REGIONSEC_GMAC0,      NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMXGBE_NIC_CFG_GPV_REGIONSEC_GMAC1,      NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMXGBE_NIC_CFG_GPV_REGIONSEC_SMMU,       NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMXGBE_NIC_CFG_GPV_REGIONSEC_HDMI,       NIC_GPV_REGIONSEC_NONSECURE);
}
