/*
 * Copyright (c) 2018-2020, Baikal Electronics JSC. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <arch_helpers.h>
#include <assert.h>
#include <bm1000_gpio.h>
#include <bm1000_private.h>
#include <drivers/arm/gicv3.h>
#include <drivers/console.h>
#include <lib/mmio.h>
#include <plat/arm/common/plat_arm.h>
#include <plat/common/platform.h>
#include <platform_def.h>

/* Clock dividers for AVLSP, based on 1200 MHz input clk */
#define AVLSP_CLK_600MHZ		 2
#define AVLSP_CLK_400MHZ		 3
#define AVLSP_CLK_300MHZ		 4
#define AVLSP_CLK_250MHZ		 5  //250MHZ needed, but we can get only 240MHZ (1200MHZ/5)
#define AVLSP_CLK_240MHZ		 5
#define AVLSP_CLK_200MHZ		 6
#define AVLSP_CLK_100MHZ		 12
#define AVLSP_CLK_50MHZ			 24
#define AVLSP_CLK_48MHZ			 25
#define AVLSP_CLK_40MHZ			 30
#define AVLSP_CLK_25MHZ			 48
#define AVLSP_CLK_10MHZ			 120
#define AVLSP_CLK_8MHZ			 150
#define AVLSP_CLK_7p35MHZ		 163
#define AVLSP_CLK_1MHZ			 1200
#define AVLSP_CLK_800KHZ		 1500

/* Clock channels */
#define MMAVLSP_CCH_GPIO		  0
#define MMAVLSP_CCH_UART1		  1
#define MMAVLSP_CCH_UART2		  2
#define MMAVLSP_CCH_APB			  3
#define MMAVLSP_CCH_SPI			  4
#define MMAVLSP_CCH_ESPI		  5
#define MMAVLSP_CCH_I2C1		  6
#define MMAVLSP_CCH_I2C2		  7
#define MMAVLSP_CCH_TIMER1		  8
#define MMAVLSP_CCH_TIMER2		  9
#define MMAVLSP_CCH_TIMER3		 10
#define MMAVLSP_CCH_TIMER4		 11
#define MMAVLSP_CCH_DMAC		 12
#define MMAVLSP_CCH_SMBUS1		 13
#define MMAVLSP_CCH_SMBUS2		 14
#define MMAVLSP_CCH_HDA_SYS_CLK		 15
#define MMAVLSP_CCH_HDA_CLK48		 16
#define MMAVLSP_CCH_MSHC_AXI		 17
#define MMAVLSP_CCH_MSHC_AHB		 18
#define MMAVLSP_CCH_MSHC_CCLK		 19
#define MMAVLSP_CCH_MSHC_BCLK		 20
#define MMAVLSP_CCH_MSHC_TMCLK		 21
#define MMAVLSP_CCH_MSHC_CQETMCLK	 22
#define MMAVLSP_CCH_HWA_CLU		 23
#define MMAVLSP_CCH_HWA_CLU_HF		 24
#define MMAVLSP_CCH_HWA_AXI_MMU		 25
#define MMAVLSP_CCH_VDU_AXI		 26
#define MMAVLSP_CCH_MMU			 27

/* Resets */
#define MMAVLSP_ASYNCRES_REG			(AVLSP_LCRU + LCRU_GPR + 0x0)
#define MMAVLSP_ASYNCRES_REG_CFG_NICS_RES	CTL_BIT(0)
#define MMAVLSP_ASYNCRES_REG_CFG_NICM_RES	CTL_BIT(1)
#define MMAVLSP_ASYNCRES_REG_DMA_NICS_RES	CTL_BIT(2)
#define MMAVLSP_ASYNCRES_REG_DMA_NICM_RES	CTL_BIT(3)
#define MMAVLSP_ASYNCRES_REG_DMAC_RES		CTL_BIT(6)
#define MMAVLSP_ASYNCRES_REG_MMU_RES		CTL_BIT(7)
#define MMAVLSP_ASYNCRES_REG_GPIO_RES		CTL_BIT(10)
#define MMAVLSP_ASYNCRES_REG_UART1_RES		CTL_BIT(11)
#define MMAVLSP_ASYNCRES_REG_UART2_RES		CTL_BIT(12)
#define MMAVLSP_ASYNCRES_REG_SPI_RES		CTL_BIT(13)
#define MMAVLSP_ASYNCRES_REG_ESPI_RES		CTL_BIT(14)
#define MMAVLSP_ASYNCRES_REG_I2C1_RES		CTL_BIT(15)
#define MMAVLSP_ASYNCRES_REG_I2C2_RES		CTL_BIT(16)
#define MMAVLSP_ASYNCRES_REG_TIMER1_RES		CTL_BIT(17)
#define MMAVLSP_ASYNCRES_REG_TIMER2_RES		CTL_BIT(18)
#define MMAVLSP_ASYNCRES_REG_TIMER3_RES		CTL_BIT(19)
#define MMAVLSP_ASYNCRES_REG_TIMER4_RES		CTL_BIT(20)
#define MMAVLSP_ASYNCRES_REG_SMBUS_I2C1_RES	CTL_BIT(21)
#define MMAVLSP_ASYNCRES_REG_SMBUS_I2C2_RES	CTL_BIT(22)
#define MMAVLSP_ASYNCRES_REG_GPIO_APB_RES	CTL_BIT(23)
#define MMAVLSP_ASYNCRES_REG_UART1_APB_RES	CTL_BIT(24)
#define MMAVLSP_ASYNCRES_REG_UART2_APB_RES	CTL_BIT(25)
#define MMAVLSP_ASYNCRES_REG_SPI_APB_RES	CTL_BIT(26)
#define MMAVLSP_ASYNCRES_REG_ESPI_APB_RES	CTL_BIT(27)
#define MMAVLSP_ASYNCRES_REG_I2C1_APB_RES	CTL_BIT(28)
#define MMAVLSP_ASYNCRES_REG_I2C2_APB_RES	CTL_BIT(29)
#define MMAVLSP_ASYNCRES_REG_TIMERS_APB_RES	CTL_BIT(30)
#define MMAVLSP_ASYNCRES_REG_I2S_APB_RES	CTL_BIT(31)

#define MMAVLSP_ASYNCRES1_REG			(AVLSP_LCRU + LCRU_GPR + 0x8)
#define MMAVLSP_ASYNCRES1_REG_HDA_RES		CTL_BIT(0)
#define MMAVLSP_ASYNCRES1_REG_MSHC_AXI_RES	CTL_BIT(1)
#define MMAVLSP_ASYNCRES1_REG_MSHC_AHB_RES	CTL_BIT(2)
#define MMAVLSP_ASYNCRES1_REG_MSHC_C_RES	CTL_BIT(3)
#define MMAVLSP_ASYNCRES1_REG_MSHC_B_RES	CTL_BIT(4)
#define MMAVLSP_ASYNCRES1_REG_MSHC_T_RES	CTL_BIT(5)
#define MMAVLSP_ASYNCRES1_REG_CQET_RES		CTL_BIT(6)
#define MMAVLSP_ASYNCRES1_REG_TUNING_SDCLK_RES	CTL_BIT(7)
#define MMAVLSP_ASYNCRES1_REG_VDU_AXI_RES	CTL_BIT(8)
#define MMAVLSP_ASYNCRES1_REG_HWA_CLU_RES	CTL_BIT(9)
#define MMAVLSP_ASYNCRES1_REG_HAW_CLU_HF_RES	CTL_BIT(10)
#define MMAVLSP_ASYNCRES1_REG_HWA_AXI_MMU_RES	CTL_BIT(11)
#define MMAVLSP_ASYNCRES1_REG_HWA_CFG_RES	CTL_BIT(12)
#define MMAVLSP_ASYNCRES1_REG_VDU_PLL_RES	CTL_BIT(13)
#define MMAVLSP_ASYNCRES1_REG_CLOCK_24_RES	CTL_BIT(14)
#define MMAVLSP_ASYNCRES1_REG_I2S_RES		CTL_BIT(15)
//#define MMAVLSP_ASYNCRES1_REG__RES	CTL_BIT()

#define MMAVLSP_MSHC_CFG_REG			(AVLSP_LCRU + LCRU_GPR + 0x20)
#define MMAVLSP_MSHC_CFG_REG_CLKDIV_SEL		CTL_BIT(16)

#define MMAVLSP_VDU_ARQOS_REG		(AVLSP_LCRU + LCRU_GPR + 0x30)
#define MMAVLSP_VDU_ARQOS_REG_ARQOS(x)		CTL_BIT_SET(x, 7, 4)

#define MMAVLSP_VDU_CACHE_AND_DOMAIN_REG	(AVLSP_LCRU + LCRU_GPR + 0x50)
#define MMAVLSP_VDU_CACHE_AND_DOMAIN_REG_ARCACHE(x)	CTL_BIT_SET(x, 3,0)
#define MMAVLSP_VDU_CACHE_AND_DOMAIN_REG_ARDOMAIN(x)	CTL_BIT_SET(x, 5,4)

#define MMAVLSP_HDA_CACHE_AND_DOMAIN_REG	(AVLSP_LCRU + LCRU_GPR + 0x38)
#define MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_AWCACHE(x)	CTL_BIT_SET(x, 3,0)
#define MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_ARCACHE(x)	CTL_BIT_SET(x, 7,4)
#define MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_AWDOMAIN(x)	CTL_BIT_SET(x, 9,8)
#define MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_ARDOMAIN(x)	CTL_BIT_SET(x, 11,10)

#define MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG	(AVLSP_LCRU + LCRU_GPR + 0x48)
#define MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_AWCACHE(x)	CTL_BIT_SET(x, 3,0)
#define MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_ARCACHE(x)	CTL_BIT_SET(x, 7,4)
#define MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_AWDOMAIN(x)	CTL_BIT_SET(x, 9,8)
#define MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_ARDOMAIN(x)	CTL_BIT_SET(x, 11,10)

#define MMAVLSP_CCH_ON(id, divider) CLKCH_ON(AVLSP_LCRU + LCRU_CMU0 + LCRU_CLKCH_OFFSET(id), divider)

#define MMAVLSP_VDU_LCRU_PLL1_RESET_GPIO_PIN	17

static const PllCtlInitValues AVLSP_LCRU_PLL_INIT = {
	0, 0, 0x60, 0x00, 0x00, 0x2c, 0x00, 0x2c
};

void mmlsp_on(void)
{
	uint32_t	avlsp_gpr1, avlsp_gpr0;

	pll_on(AVLSP_LCRU, &AVLSP_LCRU_PLL_INIT, "AVLSP_LCRU timeout!" );
	/* Clock channels, AVLSP BASE Clock 1200 MHz */
	MMAVLSP_CCH_ON(MMAVLSP_CCH_DMAC, AVLSP_CLK_200MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_MMU, AVLSP_CLK_300MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_VDU_AXI, AVLSP_CLK_240MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_HWA_CLU, AVLSP_CLK_200MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_HWA_CLU_HF, AVLSP_CLK_600MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_HWA_AXI_MMU, AVLSP_CLK_400MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_GPIO, AVLSP_CLK_8MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_I2C1, AVLSP_CLK_100MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_I2C2, AVLSP_CLK_100MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_UART1, AVLSP_CLK_7p35MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_UART2, AVLSP_CLK_7p35MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_SPI, AVLSP_CLK_50MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_ESPI, AVLSP_CLK_25MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_SMBUS1, AVLSP_CLK_50MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_SMBUS2, AVLSP_CLK_50MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_HDA_SYS_CLK, AVLSP_CLK_100MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_HDA_CLK48, AVLSP_CLK_48MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_TIMER1, AVLSP_CLK_50MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_TIMER2, AVLSP_CLK_50MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_TIMER3, AVLSP_CLK_50MHZ);
	MMAVLSP_CCH_ON(MMAVLSP_CCH_TIMER4, AVLSP_CLK_50MHZ);

#ifdef BE_MITX
	gpio_config_pin(MMAVLSP_VDU_LCRU_PLL1_RESET_GPIO_PIN);
	gpio_clear_pin(MMAVLSP_VDU_LCRU_PLL1_RESET_GPIO_PIN);
	int timeout = 1000000;
	while (timeout--);
	gpio_set_pin(MMAVLSP_VDU_LCRU_PLL1_RESET_GPIO_PIN);
#endif

	/* resets */
	avlsp_gpr0 = mmio_read_32(MMAVLSP_ASYNCRES_REG);
	avlsp_gpr0 &= ~(
			MMAVLSP_ASYNCRES_REG_CFG_NICM_RES	|
			MMAVLSP_ASYNCRES_REG_DMA_NICM_RES	|
			MMAVLSP_ASYNCRES_REG_DMA_NICS_RES	|
			MMAVLSP_ASYNCRES_REG_CFG_NICS_RES	|
			MMAVLSP_ASYNCRES_REG_GPIO_APB_RES	|
			MMAVLSP_ASYNCRES_REG_I2C1_APB_RES	|
			MMAVLSP_ASYNCRES_REG_I2C2_APB_RES	|
			MMAVLSP_ASYNCRES_REG_GPIO_RES		|
			MMAVLSP_ASYNCRES_REG_I2C1_RES		|
			MMAVLSP_ASYNCRES_REG_I2C2_RES		|
			MMAVLSP_ASYNCRES_REG_UART1_RES		|
			MMAVLSP_ASYNCRES_REG_UART2_RES		|
			MMAVLSP_ASYNCRES_REG_UART1_APB_RES	|
			MMAVLSP_ASYNCRES_REG_UART2_APB_RES	|
			MMAVLSP_ASYNCRES_REG_SPI_RES		|
			MMAVLSP_ASYNCRES_REG_ESPI_RES		|
			MMAVLSP_ASYNCRES_REG_SPI_APB_RES	|
			MMAVLSP_ASYNCRES_REG_ESPI_APB_RES	|
			MMAVLSP_ASYNCRES_REG_SMBUS_I2C1_RES	|
			MMAVLSP_ASYNCRES_REG_SMBUS_I2C2_RES	|
			MMAVLSP_ASYNCRES_REG_I2S_APB_RES	|
			//MMAVLSP_ASYNCRES_REG_DMAC_RES		|
			//MMAVLSP_ASYNCRES_REG_MMU_RES		|
			MMAVLSP_ASYNCRES_REG_TIMER1_RES		|
			MMAVLSP_ASYNCRES_REG_TIMER2_RES		|
			MMAVLSP_ASYNCRES_REG_TIMER3_RES		|
			MMAVLSP_ASYNCRES_REG_TIMER4_RES		|
			MMAVLSP_ASYNCRES_REG_TIMERS_APB_RES
			);
	mmio_write_32(MMAVLSP_ASYNCRES_REG, avlsp_gpr0);

	/* resets */
	avlsp_gpr0 = mmio_read_32(MMAVLSP_ASYNCRES_REG);
	avlsp_gpr0 &= ~(MMAVLSP_ASYNCRES_REG_MMU_RES);
	mmio_write_32(MMAVLSP_ASYNCRES_REG, avlsp_gpr0);

	avlsp_gpr1 = mmio_read_32(MMAVLSP_ASYNCRES1_REG);

	avlsp_gpr1 &= ~(MMAVLSP_ASYNCRES1_REG_VDU_AXI_RES	|
			MMAVLSP_ASYNCRES1_REG_VDU_PLL_RES	|
			MMAVLSP_ASYNCRES1_REG_HDA_RES		|
			MMAVLSP_ASYNCRES1_REG_HWA_CLU_RES	|
			MMAVLSP_ASYNCRES1_REG_HAW_CLU_HF_RES	|
			MMAVLSP_ASYNCRES1_REG_MSHC_AXI_RES	|
			MMAVLSP_ASYNCRES1_REG_MSHC_AHB_RES    	|
			MMAVLSP_ASYNCRES1_REG_MSHC_C_RES      	|
			MMAVLSP_ASYNCRES1_REG_MSHC_B_RES      	|
			MMAVLSP_ASYNCRES1_REG_MSHC_T_RES      	|
			MMAVLSP_ASYNCRES1_REG_CQET_RES	      	|
			MMAVLSP_ASYNCRES1_REG_TUNING_SDCLK_RES	|
			MMAVLSP_ASYNCRES1_REG_HWA_AXI_MMU_RES
			);

	mmio_write_32(MMAVLSP_ASYNCRES1_REG, avlsp_gpr1);

	// VDU Domain 2, cached
	mmio_write_32( MMAVLSP_VDU_CACHE_AND_DOMAIN_REG,
		       MMAVLSP_VDU_CACHE_AND_DOMAIN_REG_ARDOMAIN(2) |
		       MMAVLSP_VDU_CACHE_AND_DOMAIN_REG_ARCACHE(0xb)
			);
	mmio_write_32( MMAVLSP_VDU_ARQOS_REG,
			MMAVLSP_VDU_ARQOS_REG_ARQOS(0xf)
			);


	// HD Audio cache domain
	mmio_write_32( MMAVLSP_HDA_CACHE_AND_DOMAIN_REG,
		       MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_ARDOMAIN(0x2) |
		       MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_AWDOMAIN(0x2) |
		       MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_ARCACHE(0xb) |
		       MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_AWCACHE(0x7)
			);
	// MSHC cache domain
	mmio_write_32( MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG,
		       MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_ARDOMAIN(0x2) |
		       MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_AWDOMAIN(0x2) |
		       MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_ARCACHE(0xb) |
		       MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_AWCACHE(0x7)
			);

	// MSHC Enable frequency division
	avlsp_gpr0 = mmio_read_32(MMAVLSP_MSHC_CFG_REG);
	avlsp_gpr0 &= ~MMAVLSP_MSHC_CFG_REG_CLKDIV_SEL;
	mmio_write_32(MMAVLSP_MSHC_CFG_REG, avlsp_gpr0);
}

void mmlsp_toNSW(void)
{
	/* Prepare for non secure world (EFI, rich os) */
	SECURE_MODE(BAIKAL_NIC_AVLSP_UART_1, SECURE_MODE_OFF);
	SECURE_MODE(BAIKAL_NIC_AVLSP_UART_2, SECURE_MODE_OFF);
	/* SPI secure mode off */
	SECURE_MODE(BAIKAL_NIC_AVLSP_SPI, SECURE_MODE_OFF);
	/* VDU secure mode off, DMA - NS */
	SECURE_MODE(BAIKAL_NIC_AVLSP_VDU, SECURE_MODE_OFF);
	/* GPIO secure mode off */
	SECURE_MODE(BAIKAL_NIC_AVLSP_GPIO, SECURE_MODE_OFF);
	/* I2C secure mode off */
	SECURE_MODE(BAIKAL_NIC_AVLSP_I2C_1, SECURE_MODE_OFF);
	SECURE_MODE(BAIKAL_NIC_AVLSP_I2C_2, SECURE_MODE_OFF);
	/* SMBus secure mode off */
	SECURE_MODE(BAIKAL_NIC_AVLSP_SMBUS_1, SECURE_MODE_OFF);
	SECURE_MODE(BAIKAL_NIC_AVLSP_SMBUS_2, SECURE_MODE_OFF);
	/* I2S secure mode off */
	SECURE_MODE(BAIKAL_NIC_AVLSP_I2S, SECURE_MODE_OFF);
	/* HD audio secure mode off */
	SECURE_MODE(BAIKAL_NIC_AVLSP_HDA, SECURE_MODE_OFF);
	/* Timers secure mode off */
	SECURE_MODE(BAIKAL_NIC_AVLSP_TIMERS, SECURE_MODE_OFF);
	/* eMMC/SD Controller secure mode off */
	SECURE_MODE(BAIKAL_NIC_AVLSP_SDC, SECURE_MODE_OFF);
	/* eSPI secure mode off */
	SECURE_MODE(BAIKAL_NIC_AVLSP_ESPI, SECURE_MODE_OFF);
}
