/*
 * Copyright (c) 2018-2023, Baikal Electronics, JSC. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <lib/mmio.h>
#include <lib/utils_def.h>

#include <baikal_def.h>
#include <bm1000_cmu.h>
#include <bm1000_private.h>
#include <dw_gpio.h>

/* Clock dividers for MMAVLSP CMU0 clock channels, PLL frequency is assumed 1200 MHz */
#define MMAVLSP_CLK_7361963HZ	163
#define MMAVLSP_CLK_8MHZ	150
#define MMAVLSP_CLK_10MHZ	120
#define MMAVLSP_CLK_25MHZ	 48
#define MMAVLSP_CLK_40MHZ	 30
#define MMAVLSP_CLK_48MHZ	 25
#define MMAVLSP_CLK_50MHZ	 24
#define MMAVLSP_CLK_100MHZ	 12
#define MMAVLSP_CLK_200MHZ	  6
#define MMAVLSP_CLK_300MHZ	  4
#define MMAVLSP_CLK_400MHZ	  3
#define MMAVLSP_CLK_600MHZ	  2

void mmavlsp_init(void)
{
	const cmu_pll_ctl_vals_t mmavlsp_cmu0_pll_ctls = {
		0, 0, 0x6000000000, 0, -20, 0, -20
	};

#ifdef BAIKAL_LVDS_CLKEN_GPIO_PIN
	gpio_out_rst(MMAVLSP_GPIO32_BASE, BAIKAL_LVDS_CLKEN_GPIO_PIN);
	gpio_dir_set(MMAVLSP_GPIO32_BASE, BAIKAL_LVDS_CLKEN_GPIO_PIN);
#endif

	cmu_pll_on(MMAVLSP_CMU0_BASE, &mmavlsp_cmu0_pll_ctls);

	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_GPIO32,	    MMAVLSP_CLK_8MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_UART1,	    MMAVLSP_CLK_7361963HZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_UART2,	    MMAVLSP_CLK_7361963HZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_SPI,	    MMAVLSP_CLK_50MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_ESPI,	    MMAVLSP_CLK_25MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_I2C1,	    MMAVLSP_CLK_100MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_I2C2,	    MMAVLSP_CLK_100MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_TIMER1,	    MMAVLSP_CLK_50MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_TIMER2,	    MMAVLSP_CLK_50MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_TIMER3,	    MMAVLSP_CLK_50MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_TIMER4,	    MMAVLSP_CLK_50MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_DMACLSP,	    MMAVLSP_CLK_200MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_SMBUS1,	    MMAVLSP_CLK_50MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_SMBUS2,	    MMAVLSP_CLK_50MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_HDA_SYS,	    MMAVLSP_CLK_100MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_HDA_48,	    MMAVLSP_CLK_48MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_HWA_CLU,	    MMAVLSP_CLK_200MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_HWA_CLU_HF,  MMAVLSP_CLK_600MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_HWA_AXI_MMU, MMAVLSP_CLK_400MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_VDU_AXI,	    MMAVLSP_CLK_300MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_SMMU,	    MMAVLSP_CLK_300MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_MSHC_AXI,    MMAVLSP_CLK_200MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_MSHC_AHB,    MMAVLSP_CLK_200MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_MSHC_TX_X2,  MMAVLSP_CLK_400MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_MSHC_BCLK,   MMAVLSP_CLK_40MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_MSHC_TMCLK,  MMAVLSP_CLK_10MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_MSHC_CQETMCLK, MMAVLSP_CLK_10MHZ);

	/* Deassert reset signals */
	mmio_clrbits_32(MMAVLSP_GPR_MMRST1,
			MMAVLSP_GPR_MMRST1_NIC_CFG_S_RST  |
			MMAVLSP_GPR_MMRST1_NIC_CFG_M_RST  |
			MMAVLSP_GPR_MMRST1_NIC_S_RST	  |
			MMAVLSP_GPR_MMRST1_NIC_M_RST	  |
			MMAVLSP_GPR_MMRST1_DMACLSP_RST	  |
			MMAVLSP_GPR_MMRST1_SMMU_RST	  |
			MMAVLSP_GPR_MMRST1_GPIO_RST	  |
			MMAVLSP_GPR_MMRST1_UART1_RST	  |
			MMAVLSP_GPR_MMRST1_UART2_RST	  |
			MMAVLSP_GPR_MMRST1_SPI_RST	  |
			MMAVLSP_GPR_MMRST1_ESPI_RST	  |
			MMAVLSP_GPR_MMRST1_I2C1_RST	  |
			MMAVLSP_GPR_MMRST1_I2C2_RST	  |
			MMAVLSP_GPR_MMRST1_TIMER1_RST	  |
			MMAVLSP_GPR_MMRST1_TIMER2_RST	  |
			MMAVLSP_GPR_MMRST1_TIMER3_RST	  |
			MMAVLSP_GPR_MMRST1_TIMER4_RST	  |
			MMAVLSP_GPR_MMRST1_SMBUS1_RST	  |
			MMAVLSP_GPR_MMRST1_SMBUS2_RST	  |
			MMAVLSP_GPR_MMRST1_GPIO_APB_RST	  |
			MMAVLSP_GPR_MMRST1_UART1_APB_RST  |
			MMAVLSP_GPR_MMRST1_UART2_APB_RST  |
			MMAVLSP_GPR_MMRST1_SPI_APB_RST	  |
			MMAVLSP_GPR_MMRST1_ESPI_APB_RST	  |
			MMAVLSP_GPR_MMRST1_I2C1_APB_RST	  |
			MMAVLSP_GPR_MMRST1_I2C2_APB_RST	  |
			MMAVLSP_GPR_MMRST1_TIMERS_APB_RST |
			MMAVLSP_GPR_MMRST1_I2S_APB_RST);

	mmio_clrbits_32(MMAVLSP_GPR_MMRST2,
			MMAVLSP_GPR_MMRST2_HDA_RST	       |
			MMAVLSP_GPR_MMRST2_MSHC_AXI_RST	       |
			MMAVLSP_GPR_MMRST2_MSHC_AHB_RST	       |
			MMAVLSP_GPR_MMRST2_MSHC_C_RST	       |
			MMAVLSP_GPR_MMRST2_MSHC_B_RST	       |
			MMAVLSP_GPR_MMRST2_MSHC_T_RST	       |
			MMAVLSP_GPR_MMRST2_MSHC_CQET_RST       |
			MMAVLSP_GPR_MMRST2_MSHC_TUNE_SDCLK_RST |
			MMAVLSP_GPR_MMRST2_VDU_AXI_RST	       |
			MMAVLSP_GPR_MMRST2_HWA_CLU_RST	       |
			MMAVLSP_GPR_MMRST2_HWA_CLU_HF_RST      |
			MMAVLSP_GPR_MMRST2_HWA_AXI_MMU_RST     |
			MMAVLSP_GPR_MMRST2_VDU_PLL_RST	       |
			MMAVLSP_GPR_MMRST2_I2S_RST);

	/* VDU domain 2, cached */
	mmio_write_32(MMAVLSP_GPR_VDU_AXI,
		      MMAVLSP_GPR_VDU_AXI_ARDOMAIN(2) |
		      MMAVLSP_GPR_VDU_AXI_ARCACHE(0xb));

	mmio_write_32(MMAVLSP_GPR_VDU_AXQOS,
		      MMAVLSP_GPR_VDU_AXQOS_ARQOS(0xf));

	/* HD audio cache domain */
	mmio_write_32(MMAVLSP_GPR_HDA_AXI,
		      MMAVLSP_GPR_HDA_AXI_ARDOMAIN(2)  |
		      MMAVLSP_GPR_HDA_AXI_AWDOMAIN(2)  |
		      MMAVLSP_GPR_HDA_AXI_ARCACHE(0xb) |
		      MMAVLSP_GPR_HDA_AXI_AWCACHE(0x7));

	/* MSHC cache domain */
	mmio_write_32(MMAVLSP_GPR_MSHC_AXI,
		      MMAVLSP_GPR_MSHC_AXI_ARDOMAIN(2)	|
		      MMAVLSP_GPR_MSHC_AXI_AWDOMAIN(2)	|
		      MMAVLSP_GPR_MSHC_AXI_ARCACHE(0xb)	|
		      MMAVLSP_GPR_MSHC_AXI_AWCACHE(0x7));

	/* MSHC enable frequency division */
	mmio_clrbits_32(MMAVLSP_GPR_MSHC_CFG,
			MMAVLSP_GPR_MSHC_CFG_CLKDIV_SEL);

	/* Enable non-secure access */
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_GPIO32, NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_SMBUS1, NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_SMBUS2, NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_I2S,    NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_SPI,    NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_I2C1,   NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_I2C2,   NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_UART1,  NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_UART2,  NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_ESPI,   NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_HDA,    NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_SDC,    NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_TIMERS, NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_VDU,    NIC_GPV_REGIONSEC_NONSECURE);
}
