/*
 * Copyright (c) 2018-2021, Baikal Electronics, JSC. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <lib/mmio.h>
#include <lib/utils_def.h>

#include <baikal_def.h>
#include <bm1000_cmu.h>
#include <bm1000_private.h>
#include <dw_gpio.h>

/* Resets */
#define MMAVLSP_RESET1_REG			(MMAVLSP_GPR_BASE + 0x00)
#define MMAVLSP_RESET1_REG_CFG_NICS_RES		BIT(0)
#define MMAVLSP_RESET1_REG_CFG_NICM_RES		BIT(1)
#define MMAVLSP_RESET1_REG_DMA_NICS_RES		BIT(2)
#define MMAVLSP_RESET1_REG_DMA_NICM_RES		BIT(3)
#define MMAVLSP_RESET1_REG_DMAC_RES		BIT(6)
#define MMAVLSP_RESET1_REG_SMMU_RES		BIT(7)
#define MMAVLSP_RESET1_REG_GPIO_RES		BIT(10)
#define MMAVLSP_RESET1_REG_UART1_RES		BIT(11)
#define MMAVLSP_RESET1_REG_UART2_RES		BIT(12)
#define MMAVLSP_RESET1_REG_SPI_RES		BIT(13)
#define MMAVLSP_RESET1_REG_ESPI_RES		BIT(14)
#define MMAVLSP_RESET1_REG_I2C1_RES		BIT(15)
#define MMAVLSP_RESET1_REG_I2C2_RES		BIT(16)
#define MMAVLSP_RESET1_REG_TIMER1_RES		BIT(17)
#define MMAVLSP_RESET1_REG_TIMER2_RES		BIT(18)
#define MMAVLSP_RESET1_REG_TIMER3_RES		BIT(19)
#define MMAVLSP_RESET1_REG_TIMER4_RES		BIT(20)
#define MMAVLSP_RESET1_REG_SMBUS1_RES		BIT(21)
#define MMAVLSP_RESET1_REG_SMBUS2_RES		BIT(22)
#define MMAVLSP_RESET1_REG_GPIO_APB_RES		BIT(23)
#define MMAVLSP_RESET1_REG_UART1_APB_RES	BIT(24)
#define MMAVLSP_RESET1_REG_UART2_APB_RES	BIT(25)
#define MMAVLSP_RESET1_REG_SPI_APB_RES		BIT(26)
#define MMAVLSP_RESET1_REG_ESPI_APB_RES		BIT(27)
#define MMAVLSP_RESET1_REG_I2C1_APB_RES		BIT(28)
#define MMAVLSP_RESET1_REG_I2C2_APB_RES		BIT(29)
#define MMAVLSP_RESET1_REG_TIMERS_APB_RES	BIT(30)
#define MMAVLSP_RESET1_REG_I2S_APB_RES		BIT(31)

#define MMAVLSP_RESET2_REG			(MMAVLSP_GPR_BASE + 0x08)
#define MMAVLSP_RESET2_REG_HDA_RES		BIT(0)
#define MMAVLSP_RESET2_REG_MSHC_AXI_RES		BIT(1)
#define MMAVLSP_RESET2_REG_MSHC_AHB_RES		BIT(2)
#define MMAVLSP_RESET2_REG_MSHC_C_RES		BIT(3)
#define MMAVLSP_RESET2_REG_MSHC_B_RES		BIT(4)
#define MMAVLSP_RESET2_REG_MSHC_T_RES		BIT(5)
#define MMAVLSP_RESET2_REG_MSHC_CQET_RES	BIT(6)
#define MMAVLSP_RESET2_REG_TUNING_SDCLK_RES	BIT(7)
#define MMAVLSP_RESET2_REG_VDU_AXI_RES		BIT(8)
#define MMAVLSP_RESET2_REG_HWA_CLU_RES		BIT(9)
#define MMAVLSP_RESET2_REG_HWA_CLU_HF_RES	BIT(10)
#define MMAVLSP_RESET2_REG_HWA_AXI_MMU_RES	BIT(11)
#define MMAVLSP_RESET2_REG_HWA_CFG_RES		BIT(12)
#define MMAVLSP_RESET2_REG_VDU_PLL_RES		BIT(13)
#define MMAVLSP_RESET2_REG_CLOCK_24_RES		BIT(14)
#define MMAVLSP_RESET2_REG_I2S_RES		BIT(15)

#define MMAVLSP_MSHC_CFG_REG			(MMAVLSP_GPR_BASE + 0x20)
#define MMAVLSP_MSHC_CFG_REG_CLKDIV_SEL		BIT(16)

#define MMAVLSP_VDU_ARQOS_REG			(MMAVLSP_GPR_BASE + 0x30)
#define MMAVLSP_VDU_ARQOS_REG_ARQOS(x)		SETMASK(x, 7, 4)

#define MMAVLSP_VDU_CACHE_AND_DOMAIN_REG	(MMAVLSP_GPR_BASE + 0x50)
#define MMAVLSP_VDU_CACHE_AND_DOMAIN_REG_ARCACHE(x)	SETMASK(x, 3, 0)
#define MMAVLSP_VDU_CACHE_AND_DOMAIN_REG_ARDOMAIN(x)	SETMASK(x, 5, 4)

#define MMAVLSP_HDA_CACHE_AND_DOMAIN_REG	(MMAVLSP_GPR_BASE + 0x38)
#define MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_AWCACHE(x)	SETMASK(x,  3,  0)
#define MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_ARCACHE(x)	SETMASK(x,  7,  4)
#define MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_AWDOMAIN(x)	SETMASK(x,  9,  8)
#define MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_ARDOMAIN(x)	SETMASK(x, 11, 10)

#define MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG	(MMAVLSP_GPR_BASE + 0x48)
#define MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_AWCACHE(x)	SETMASK(x,  3,  0)
#define MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_ARCACHE(x)	SETMASK(x,  7,  4)
#define MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_AWDOMAIN(x)	SETMASK(x,  9,  8)
#define MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_ARDOMAIN(x)	SETMASK(x, 11, 10)

/* Clock dividers for MMAVLSP CMU0 clock channels, PLL frequency is assumed 1200 MHz */
#define MMAVLSP_CLK_600MHZ	   2
#define MMAVLSP_CLK_400MHZ	   3
#define MMAVLSP_CLK_300MHZ	   4
#define MMAVLSP_CLK_200MHZ	   6
#define MMAVLSP_CLK_100MHZ	  12
#define MMAVLSP_CLK_50MHZ	  24
#define MMAVLSP_CLK_48MHZ	  25
#define MMAVLSP_CLK_25MHZ	  48
#define MMAVLSP_CLK_8MHZ	 150
#define MMAVLSP_CLK_7361963HZ	 163

void mmavlsp_init(void)
{
	const cmu_pll_ctl_vals_t mmavlsp_cmu0_pll_ctls = {
		0, 0, 0x60, 0, 0, 0x2c, 0, 0x2c
	};

	cmu_pll_on(MMAVLSP_CMU0_BASE, &mmavlsp_cmu0_pll_ctls);

	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_GPIO32,	    MMAVLSP_CLK_8MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_UART1,	    MMAVLSP_CLK_7361963HZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_UART2,	    MMAVLSP_CLK_7361963HZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_SPI,	    MMAVLSP_CLK_50MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_ESPI,	    MMAVLSP_CLK_25MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_I2C1,	    MMAVLSP_CLK_100MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_I2C2,	    MMAVLSP_CLK_100MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_TIMER1,	    MMAVLSP_CLK_50MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_TIMER2,	    MMAVLSP_CLK_50MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_TIMER3,	    MMAVLSP_CLK_50MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_TIMER4,	    MMAVLSP_CLK_50MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_DMAC,	    MMAVLSP_CLK_200MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_SMBUS1,	    MMAVLSP_CLK_50MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_SMBUS2,	    MMAVLSP_CLK_50MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_HDA_SYS,	    MMAVLSP_CLK_100MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_HDA_48,	    MMAVLSP_CLK_48MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_HWA_CLU,	    MMAVLSP_CLK_200MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_HWA_CLU_HF,  MMAVLSP_CLK_600MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_HWA_AXI_MMU, MMAVLSP_CLK_400MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_VDU_AXI,	    MMAVLSP_CLK_300MHZ);
	cmu_clkch_enable_by_base(MMAVLSP_CMU0_CLKCHCTL_SMMU,	    MMAVLSP_CLK_300MHZ);

#ifdef BAIKAL_LVDS_CLKEN_GPIO_PIN
	gpio_out_rst(MMAVLSP_GPIO32_BASE, BAIKAL_LVDS_CLKEN_GPIO_PIN);
	gpio_dir_set(MMAVLSP_GPIO32_BASE, BAIKAL_LVDS_CLKEN_GPIO_PIN);
#endif

	/* Deassert reset signals */
	mmio_clrbits_32(MMAVLSP_RESET1_REG,
			MMAVLSP_RESET1_REG_CFG_NICS_RES	  |
			MMAVLSP_RESET1_REG_CFG_NICM_RES	  |
			MMAVLSP_RESET1_REG_DMA_NICS_RES	  |
			MMAVLSP_RESET1_REG_DMA_NICM_RES	  |
			MMAVLSP_RESET1_REG_DMAC_RES	  |
			MMAVLSP_RESET1_REG_SMMU_RES	  |
			MMAVLSP_RESET1_REG_GPIO_RES	  |
			MMAVLSP_RESET1_REG_UART1_RES	  |
			MMAVLSP_RESET1_REG_UART2_RES	  |
			MMAVLSP_RESET1_REG_SPI_RES	  |
			MMAVLSP_RESET1_REG_ESPI_RES	  |
			MMAVLSP_RESET1_REG_I2C1_RES	  |
			MMAVLSP_RESET1_REG_I2C2_RES	  |
			MMAVLSP_RESET1_REG_TIMER1_RES	  |
			MMAVLSP_RESET1_REG_TIMER2_RES	  |
			MMAVLSP_RESET1_REG_TIMER3_RES	  |
			MMAVLSP_RESET1_REG_TIMER4_RES	  |
			MMAVLSP_RESET1_REG_SMBUS1_RES	  |
			MMAVLSP_RESET1_REG_SMBUS2_RES	  |
			MMAVLSP_RESET1_REG_GPIO_APB_RES	  |
			MMAVLSP_RESET1_REG_UART1_APB_RES  |
			MMAVLSP_RESET1_REG_UART2_APB_RES  |
			MMAVLSP_RESET1_REG_SPI_APB_RES	  |
			MMAVLSP_RESET1_REG_ESPI_APB_RES	  |
			MMAVLSP_RESET1_REG_I2C1_APB_RES	  |
			MMAVLSP_RESET1_REG_I2C2_APB_RES	  |
			MMAVLSP_RESET1_REG_TIMERS_APB_RES |
			MMAVLSP_RESET1_REG_I2S_APB_RES);

	mmio_clrbits_32(MMAVLSP_RESET2_REG,
			MMAVLSP_RESET2_REG_HDA_RES	    |
			MMAVLSP_RESET2_REG_MSHC_AXI_RES	    |
			MMAVLSP_RESET2_REG_MSHC_AHB_RES	    |
			MMAVLSP_RESET2_REG_MSHC_C_RES	    |
			MMAVLSP_RESET2_REG_MSHC_B_RES	    |
			MMAVLSP_RESET2_REG_MSHC_T_RES	    |
			MMAVLSP_RESET2_REG_MSHC_CQET_RES    |
			MMAVLSP_RESET2_REG_TUNING_SDCLK_RES |
			MMAVLSP_RESET2_REG_VDU_AXI_RES	    |
			MMAVLSP_RESET2_REG_HWA_CLU_RES	    |
			MMAVLSP_RESET2_REG_HWA_CLU_HF_RES   |
			MMAVLSP_RESET2_REG_HWA_AXI_MMU_RES  |
			MMAVLSP_RESET2_REG_VDU_PLL_RES	    |
			MMAVLSP_RESET2_REG_I2S_RES);

	/* VDU domain 2, cached */
	mmio_write_32(MMAVLSP_VDU_CACHE_AND_DOMAIN_REG,
		      MMAVLSP_VDU_CACHE_AND_DOMAIN_REG_ARDOMAIN(2) |
		      MMAVLSP_VDU_CACHE_AND_DOMAIN_REG_ARCACHE(0xb));

	mmio_write_32(MMAVLSP_VDU_ARQOS_REG,
		      MMAVLSP_VDU_ARQOS_REG_ARQOS(0xf));

	/* HD audio cache domain */
	mmio_write_32(MMAVLSP_HDA_CACHE_AND_DOMAIN_REG,
		      MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_ARDOMAIN(2)  |
		      MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_AWDOMAIN(2)  |
		      MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_ARCACHE(0xb) |
		      MMAVLSP_HDA_CACHE_AND_DOMAIN_REG_AWCACHE(0x7));

	/* MSHC cache domain */
	mmio_write_32(MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG,
		      MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_ARDOMAIN(2)  |
		      MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_AWDOMAIN(2)  |
		      MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_ARCACHE(0xb) |
		      MMAVLSP_MSHC_CACHE_AND_DOMAIN_REG_AWCACHE(0x7));

	/* MSHC enable frequency division */
	mmio_clrbits_32(MMAVLSP_MSHC_CFG_REG,
			MMAVLSP_MSHC_CFG_REG_CLKDIV_SEL);

	/* Enable non-secure access */
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_GPIO32, NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_SMBUS1, NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_SMBUS2, NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_I2S,    NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_SPI,    NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_I2C1,   NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_I2C2,   NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_UART1,  NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_UART2,  NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_ESPI,   NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_HDA,    NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_SDC,    NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_TIMERS, NIC_GPV_REGIONSEC_NONSECURE);
	mmio_write_32(MMAVLSP_NIC_CFG_GPV_REGIONSEC_VDU,    NIC_GPV_REGIONSEC_NONSECURE);
}
